from pydantic import BaseModel, Field
from typing import List


class CodeFile(BaseModel):
    """Represents a code file in the Autonoma system."""
    path: str = Field(description="The full path to the code file.")
    content: str = Field(description="The textual content of the code file.")


class CodeChange(BaseModel):
    """Represents a specific change (e.g., new content) to a code file."""
    path: str = Field(description="The full path to the file being changed.")
    code: str = Field(description="The new code content for the file.")


class GeneratedCode(BaseModel):
    """
    Represents a collection of code changes, typically generated by an LLM or coding tool.
    This structure is often used to propose modifications to one or more files.
    """
    code_changes: List[CodeChange] = Field(default_factory=list, description="A list of CodeChange objects detailing the modifications.")
